### ISSUE TITLE
Procedure template front-end

### ISSUE THREAD

**Issue by evan-meyer** [UIOWA5830SP19/SPP400#69]
Create the front-end for the procedure template. Simple form that can be extended for more steps using JavaScript.

**Comment by adm41597** [comment]
I think it'll be a modified viewflow thibg

Also, as the issue describes, the page should be built with the expectation that it'll have JavaScript elements later on that allow for dynamically adding new fields

For now I think the main fields it should have are 
- procedure name
- a way to add a time limit (Ie how blood tests "go bad")
- expected procedure date
- notes 

I'm sure there's more but that's what I can think of off the top of my head. I'd say base the page around creating a blood-test procedure since that's an easy one to understand and has most of the attributes other procedures will have
